#!/bin/bash
# usage: $0 (spi|volatile) /dev/ttyXXX

if [ "$XILINX_BIN" == "" ]; then
	XILINX_BIN=/media/user/9cdf347e-3d25-47b7-8615-025afec3f82b/xilinx/14.7/ISE_DS/ISE/bin/lin64/
fi;
IMPACT_PATH="$XILINX_BIN"/impact
PROMGEN_PATH="$XILINX_BIN"/promgen
TEMP_SVF_PATH=a.svf
TEMP_MCS_PATH=spiflash.mcs
BITFILE_PATH="$(echo top*.bit)"
CYCLES_PER_BIT=1

flash_spi() {
	CYCLES_PER_BIT=3
	"$PROMGEN_PATH" -spi -p mcs -o "$TEMP_MCS_PATH" -s 4096 -u 0 "$BITFILE_PATH" -w
	"$IMPACT_PATH" -batch <<EOF
setMode -bscan
setCable -p svf -file $TEMP_SVF_PATH
addDevice -p 1 -file $BITFILE_PATH
attachflash -position 1 -spi W25Q32BV
assignfiletoattachedflash -position 1 -file $TEMP_MCS_PATH
program -p 1 -dataWidth 4 -spionly -e -loadfpga
quit
EOF
	echo
}
flash_volatile() {
	"$IMPACT_PATH" -batch <<EOF
setMode -bscan
setCable -p svf -file $TEMP_SVF_PATH
addDevice -p 1 -file $BITFILE_PATH
program -e -p 1
quit
EOF
	echo
}
if [ "$1" == "gensvf" ]; then
	flash_$2
	echo "generated $TEMP_SVF_PATH"
else
	flash_$1 && /persist/vhdl/drivers/svfplayer -u "$2" "$CYCLES_PER_BIT" < "$TEMP_SVF_PATH"
fi;
