# TCL File Generated by Component Editor 15.1
# Thu Feb 25 21:23:41 UTC 2016
# DO NOT MODIFY


# 
# stream2hps "stream2hps" v1.0
#  2016.02.25.21:23:41
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module stream2hps
# 
set_module_property DESCRIPTION ""
set_module_property NAME stream2hps
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP asdfg
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME stream2hps
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL stream2hps
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file stream2hps.vhd VHDL PATH stream2hps.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock avalonclk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock avalonclk
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly true
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master addr address Output 32
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master waitrequest waitrequest Input 1
add_interface_port avalon_master burstcount burstcount Output 6
add_interface_port avalon_master writedata writedata Output 64


# 
# connection point avalonclk
# 
add_interface avalonclk clock end
set_interface_property avalonclk clockRate 0
set_interface_property avalonclk ENABLED true
set_interface_property avalonclk EXPORT_OF ""
set_interface_property avalonclk PORT_NAME_MAP ""
set_interface_property avalonclk CMSIS_SVD_VARIABLES ""
set_interface_property avalonclk SVD_ADDRESS_GROUP ""

add_interface_port avalonclk clk clk Input 1


# 
# connection point confclk
# 
add_interface confclk clock end
set_interface_property confclk clockRate 0
set_interface_property confclk ENABLED true
set_interface_property confclk EXPORT_OF ""
set_interface_property confclk PORT_NAME_MAP ""
set_interface_property confclk CMSIS_SVD_VARIABLES ""
set_interface_property confclk SVD_ADDRESS_GROUP ""

add_interface_port confclk confclk clk Input 1


# 
# connection point conf
# 
add_interface conf conduit end
set_interface_property conf associatedClock confclk
set_interface_property conf associatedReset reset
set_interface_property conf ENABLED true
set_interface_property conf EXPORT_OF ""
set_interface_property conf PORT_NAME_MAP ""
set_interface_property conf CMSIS_SVD_VARIABLES ""
set_interface_property conf SVD_ADDRESS_GROUP ""

add_interface_port conf conf export Input 64


# 
# connection point dataclk
# 
add_interface dataclk clock end
set_interface_property dataclk clockRate 0
set_interface_property dataclk ENABLED true
set_interface_property dataclk EXPORT_OF ""
set_interface_property dataclk PORT_NAME_MAP ""
set_interface_property dataclk CMSIS_SVD_VARIABLES ""
set_interface_property dataclk SVD_ADDRESS_GROUP ""

add_interface_port dataclk dataclk clk Input 1


# 
# connection point datain
# 
add_interface datain conduit end
set_interface_property datain associatedClock dataclk
set_interface_property datain associatedReset ""
set_interface_property datain ENABLED true
set_interface_property datain EXPORT_OF ""
set_interface_property datain PORT_NAME_MAP ""
set_interface_property datain CMSIS_SVD_VARIABLES ""
set_interface_property datain SVD_ADDRESS_GROUP ""

add_interface_port datain datain export Input 64


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint ""
set_interface_property irq associatedReset reset
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq int0 irq Output 1


# 
# connection point info
# 
add_interface info conduit end
set_interface_property info associatedClock confclk
set_interface_property info associatedReset reset
set_interface_property info ENABLED true
set_interface_property info EXPORT_OF ""
set_interface_property info PORT_NAME_MAP ""
set_interface_property info CMSIS_SVD_VARIABLES ""
set_interface_property info SVD_ADDRESS_GROUP ""

add_interface_port info info export Output 32

