# TCL File Generated by Component Editor 13.1
# Sat Mar 15 20:38:35 PDT 2014
# DO NOT MODIFY


# 
# memread "memread" v1.0
#  2014.03.15.20:38:35
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module memread
# 
set_module_property DESCRIPTION ""
set_module_property NAME memread
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP asdfg
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME memread
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL memread
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file memread.vhd VHDL PATH memread.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point master
# 
add_interface master avalon start
set_interface_property master addressUnits SYMBOLS
set_interface_property master associatedClock clock
set_interface_property master associatedReset reset_sink
set_interface_property master bitsPerSymbol 8
set_interface_property master burstOnBurstBoundariesOnly false
set_interface_property master burstcountUnits WORDS
set_interface_property master doStreamReads false
set_interface_property master doStreamWrites false
set_interface_property master holdTime 0
set_interface_property master linewrapBursts false
set_interface_property master maximumPendingReadTransactions 0
set_interface_property master readLatency 0
set_interface_property master readWaitTime 1
set_interface_property master setupTime 0
set_interface_property master timingUnits Cycles
set_interface_property master writeWaitTime 0
set_interface_property master ENABLED true
set_interface_property master EXPORT_OF ""
set_interface_property master PORT_NAME_MAP ""
set_interface_property master CMSIS_SVD_VARIABLES ""
set_interface_property master SVD_ADDRESS_GROUP ""

add_interface_port master waitrequest waitrequest Input 1
add_interface_port master read read Output 1
add_interface_port master readdata readdata Input 64
add_interface_port master addr address Output 32
add_interface_port master readdatavalid readdatavalid Input 1
add_interface_port master burstcount burstcount Output 6


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink fake_rst reset Input 1


# 
# connection point c1
# 
add_interface c1 conduit end
set_interface_property c1 associatedClock clock
set_interface_property c1 associatedReset reset_sink
set_interface_property c1 ENABLED true
set_interface_property c1 EXPORT_OF ""
set_interface_property c1 PORT_NAME_MAP ""
set_interface_property c1 CMSIS_SVD_VARIABLES ""
set_interface_property c1 SVD_ADDRESS_GROUP ""

add_interface_port c1 conduit1 export Input 32


# 
# connection point c2
# 
add_interface c2 conduit end
set_interface_property c2 associatedClock clock
set_interface_property c2 associatedReset reset_sink
set_interface_property c2 ENABLED true
set_interface_property c2 EXPORT_OF ""
set_interface_property c2 PORT_NAME_MAP ""
set_interface_property c2 CMSIS_SVD_VARIABLES ""
set_interface_property c2 SVD_ADDRESS_GROUP ""

add_interface_port c2 conduit2 export Output 32


# 
# connection point rd_en
# 
add_interface rd_en conduit end
set_interface_property rd_en associatedClock clock
set_interface_property rd_en associatedReset ""
set_interface_property rd_en ENABLED true
set_interface_property rd_en EXPORT_OF ""
set_interface_property rd_en PORT_NAME_MAP ""
set_interface_property rd_en CMSIS_SVD_VARIABLES ""
set_interface_property rd_en SVD_ADDRESS_GROUP ""

add_interface_port rd_en rd_en export Input 1


# 
# connection point rdclk
# 
add_interface rdclk clock end
set_interface_property rdclk clockRate 0
set_interface_property rdclk ENABLED true
set_interface_property rdclk EXPORT_OF ""
set_interface_property rdclk PORT_NAME_MAP ""
set_interface_property rdclk CMSIS_SVD_VARIABLES ""
set_interface_property rdclk SVD_ADDRESS_GROUP ""

add_interface_port rdclk rdclk clk Input 1


# 
# connection point rst_addr
# 
add_interface rst_addr conduit end
set_interface_property rst_addr associatedClock clock
set_interface_property rst_addr associatedReset ""
set_interface_property rst_addr ENABLED true
set_interface_property rst_addr EXPORT_OF ""
set_interface_property rst_addr PORT_NAME_MAP ""
set_interface_property rst_addr CMSIS_SVD_VARIABLES ""
set_interface_property rst_addr SVD_ADDRESS_GROUP ""

add_interface_port rst_addr rst export Input 1

